# @package _global_
model:
  _target_: src.models.two_step_estimators.AIPTWINFs
  name: aiptw_infs

  nuisance_hid_dim_multiplier: 10    # ratio between the dimentionalities of the representation and the outcome

  # nuisance hparams
  nuisance_count_bins: ???           # number of knots for nuisance, n_{\text{knots,N}}
  noise_std_X: ???                   # noise regularization for covariates, \sigma^2_x
  noise_std_Y: ???                   # noise regularization for outcomes, \sigma^2_y
  nuisance_lr: ???                   # learning rate for the nuisance flow (CNF), \eta_\text{N}
  batch_size: ???                    # batch size for the nuisance network, b_N

  num_epochs: 200                   # n_{\text{iter,N}}
  num_burn_in_epochs: ${model.num_epochs}
  prop_alpha: 1.0                   # \alpha
  clip_prop: 0.05                   # drop observations with too low propensity (for the IPTW / A-IPTW objective)

  # target hparams
  target_mode:
  target_count_bins:
  target_lr: 0.005
  target_batch_size: 64
  target_hid_layers: 1
  target_num_epochs: ${model.num_epochs}
  target_noise_std_X:
  target_gamma: 0.995                  # EMA of model weights for target

  # Tuning
  tune_hparams: False
  tune_range: 50                     # number of trials for random search
  tune_type: choice