# @package _global_
model:
  nuisance_count_bins: 10            # number of knots for nuisance, n_{\text{knots,N}}
  noise_std_X: 0.01                  # noise regularization for covariates, \sigma^2_x
  noise_std_Y: 0.0                 # noise regularization for outcomes, \sigma^2_y
  nuisance_lr: 0.001                # learning rate for the nuisance flow (CNF), \eta_\text{N}
  batch_size: 64                    # batch size for the nuisance network, b_N

  target_count_bins: 10
  dim_cov: 3